steps:
- name: 'node:14'
  entrypoint: yarn
  args: ['install']
- name: 'node:14'
  entrypoint: yarn
  args: ['generate']
- name: 'node:14'
  entrypoint: npm
  args: ['prune', '--production']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/ssr", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/ssr"]
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  # Parallel Uploading
  - "-m"
  - "-h"
  - "Cache-Control:public, max-age=604800"
  #  Synchronize content of two buckets/directories
  - "rsync"
  # Synchronized recursively
  - "-r"
  # Compute Checksum
  - "-c"
  # Delete extra files
  - "-d"
  # Local Dir
  - "./.nuxt/dist/client"
  # Remote Bucket
  - "gs://static.cytoid.io"
images:
  - gcr.io/$PROJECT_ID/ssr
timeout: 1200s
