name: Build and Publish the Docker Image
on:
  push:
    branches:
      - master
env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: ssr
  REGISTRY_HOSTNAME: gcr.io
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  NODE_ENV: production
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install Dependencies
        run: yarn install --production=false
      - name: Build API
        run: yarn build
      - name: Prune Dev Dependencies
        run: npm prune --production
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      - name: Build Docker Image
        run: |
          docker build \
            -t "$REGISTRY_HOSTNAME"/"$GCP_PROJECT"/"$IMAGE" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
      - name: Publish Docker Image
        run: |
          docker push $REGISTRY_HOSTNAME/$GCP_PROJECT/$IMAGE
      - name: 'gcr.io/cloud-builders/gsutil'
        run: gsutil -m -h "Cache-Control:public, max-age=604800" rsync -r -c -d ./.nuxt/dist/client gs://static.cytoid.io
