name: Build and Publish the Docker Image
on:
  push:
    branches:
      - main
env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: ssr
  REGISTRY_HOSTNAME: ghcr.io
  NODE_ENV: production
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    steps:
      # - name: Log in to registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      # - name: Cache node_modules
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install Dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build Nuxt App
        run: yarn build

      # - name: Prune Dev Dependencies
      #   run: npm prune --production

      # - name: Build Docker Image
      #   run: |
      #     docker build \
      #       -t "$REGISTRY_HOSTNAME"/cytoid/"$IMAGE" \
      #       --build-arg GITHUB_SHA="$GITHUB_SHA" \
      #       --build-arg GITHUB_REF="$GITHUB_REF" .

      # - name: Publish Docker Image
      #   run: |
      #     docker push "$REGISTRY_HOSTNAME"/cytoid/"$IMAGE"

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      # - name: Publish
      #   uses: cloudflare/pages-action@1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: cytoid
      #     directory: ./.output/public
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
